### ISSUE TITLE
404 in the FAQ

### ISSUE THREAD

**Issue by dngray** [etesync/etebase-docs#44]
Hi,

I found a 404 in the [FAQ](https://www.etesync.com/faq), specifically the DAVdroid link.

> With that being said, there could still be bugs in the client, however, EteSync is based on the widely used [DAVdroid](https://davdroid.bitfire.at/), which reduces the likeliness of a bug in the client. If you do encounter one, [please let us know](https://www.etesync.com/faq/#doesnt-work).

DAVdroid should probably be [DAVx⁵](https://www.davx5.com/) as the project renamed some time ago.

**Comment by tasn** [comment]
Thanks, fixed!
