### ISSUE TITLE
Relative links can sometimes be broken

### ISSUE THREAD

**Issue by elias-pap** [etesync/etebase-docs#57]
All relative links of https://docs.etebase.com/ suffer from the [trailing slash](https://github.com/slorber/trailing-slash-guide) issue. For more info see https://github.com/facebook/docusaurus/issues/5250 and [Common problems -> 404 issues](https://github.com/slorber/trailing-slash-guide#intro)

To reproduce:
* Visit https://docs.etebase.com/. Click on Getting Started --> Quickstart, then click on "create users" link. The link works correctly and navigates to https://docs.etebase.com/guides/basic_authentication#signup
* Now visit https://docs.etebase.com/quickstart directly (observe how a trailing slash is appended to the browser's url). All relative links of this page are now broken. E.g. click on "create users" link. It tries to redirect to https://docs.etebase.com/quickstart/guides/basic_authentication#signup which does not exist (404-like error).

Possible solutions:
* Change all relative links to absolute links
* Keep relative links and implement one of the solutions described [here](https://github.com/slorber/trailing-slash-guide/blob/main/docs/Solutions.md). E.g. update docusaurus to the latest version and leverage the [trailingSlash option](https://docusaurus.io/docs/api/docusaurus-config#trailing-slash) (setting `trailingSlash: true` in `docusaurus.config.js` might do the job).

Note that this is not reproducible locally, since the docs are served on `localhost:3000` (and not `localhost:3000/`).

I'm open to submit a PR for this after a solution is chosen.

**Comment by tasn** [comment]
Grrrr, thanks! I'm not happy with changing relative links to absolute, but I also don't want trailing slash to be true. :( 

I can see it being correct in the sidebar and many other places. I wonder what's the right way to fix it? What do you think (given my comment)

**Comment by elias-pap** [comment]
Are you self-hosting the docs ? If so, you can [tweak the nginx config](https://serverfault.com/a/691207) (or the config of the reverse proxy you're using) to not append trailing slashes.

Alternatively, you could deploy to Github pages or [some other Jamstack provider](https://docusaurus.io/docs/deployment#choosing-a-hosting-provider) that plays well with docusaurs.

**Comment by tasn** [comment]
Happy to setup github pages if you're willing to help.

**Comment by elias-pap** [comment]
Opened https://github.com/etesync/etebase-docs/pull/58

**Comment by tasn** [comment]
Great, thanks! Made one comment, but good otherwise.
