### ISSUE TITLE
Invalid link overview (list of existing collection types)

### ISSUE THREAD

**Issue by petrhejna** [etesync/etebase-docs#8]
In the doc file https://github.com/etesync/etebase-docs/blob/master/docs/overview.md (https://docs.etebase.com/overview/)

In the sentence
> 
In addition to creating your own types, you can also use **existing types** as long as you follow their specifications.

The link is broken.

Linked to: https://github.com/etesync/etesync-notes/issues/55

**Comment by petrhejna** [comment]
It should probably link to: https://docs.etebase.com/type-sepcs/introduction

**Comment by tasn** [comment]
I just tested it. The link isn't broken, it leads to https://docs.etebase.com/type-sepcs/introduction as you suggested.
