### ISSUE TITLE
Missing notes collecton types specification

### ISSUE THREAD

**Issue by petrhejna** [etesync/etebase-docs#9]
Similar to calendar (https://docs.etebase.com/type-sepcs/calendar)

**Comment by petrhejna** [comment]
Based on https://github.com/etesync/etesync-notes/blob/b23f9b064d7f7f3b9955f4ce94beb58ba8f79f18/src/constants/index.ts

I assume the collection type is: `etebase.md.note`

**Comment by petrhejna** [comment]
Lines to https://github.com/etesync/etesync-notes/issues/55

**Comment by petrhejna** [comment]
I have also figured out, that notes are not (apparently) using any type in `meta`.

**Comment by tasn** [comment]
I just added some documentation for notes based on what we use in EteSync Notes. The notes type is still evolving, but what's there is already stable and good to go.
